name: Count Lines of Code

on:
  pull_request:
    branches: [ main]

jobs:
  cloc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Count Lines of Code with additional options
        uses: djdefi/cloc-action@main
        with:
          options: --exclude-dir=tests,tool --exclude-lang=YAML,'Jupyter Notebook',SVG --md --report-file=cloc.md

      - name: Add comment to PR
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const clocOutput = fs.readFileSync('cloc.md', 'utf8');

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${clocOutput}`
            });

